# Generated by Django 5.2.1 on 2025-06-02 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0002_initial'),
        ('invitations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='cohort',
            field=models.ForeignKey(blank=True, help_text='Only required for students.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cohorts.cohort'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='program_type',
            field=models.CharField(choices=[('certificate', 'Certificate'), ('diploma', 'Diploma')], help_text='Only required for students.', max_length=20, null=True),
        ),
    ]
