# Generated by Django 5.2.1 on 2025-07-20 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0004_alter_invitation_options_invitation_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='program_type',
        ),
    ]
