version: '3.8'

services:
  api:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 4
    volumes:
      - logs:/app/logs
      - staticfiles:/app/staticfiles
    ports:
      - 8020:8000
    environment:
      - DJANGO_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5

  qcluster:
    build: .
    exclude_from_hc: true
    command: python manage.py qcluster
    environment:
      - DJANGO_ENV=production
    depends_on:
      - api

volumes:
  logs:
  staticfiles:

