[phases.setup]
nixPkgs = ["python312", "python312Packages.pip", "python312Packages.gunicorn"]

[phases.install]
cmds = [
  "pip install -r requirements.txt --break-system-packages"
]

[phases.build]
cmds = [
  "python manage.py collectstatic --noinput",
  "python manage.py migrate --noinput",
  "python manage.py createcachetable",
  "python manage.py createdefaultadmin"
]

[start]
cmd = "gunicorn config.wsgi:application --bind 0.0.0.0:8000"