[phases.setup]
nixPkgs = ["python312", "poetry"]

[phases.install]
cmds = [
  "poetry install --no-dev --no-interactive --no-ansi"
]

[phases.build]
cmds = [
  "python manage.py collectstatic --noinput",
  "python manage.py migrate --noinput",
  "python manage.py createcachetable",
  "python manage.py createdefaultadmin"
]

[start]
cmd = "gunicorn config.wsgi:application --bind 0.0.0.0:${PORT:-8000}"