# Generated by Django 5.2.1 on 2026-05-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('class_starting', 'Class Starting'), ('test_created', 'Test Created'), ('test_published', 'Test Published'), ('test_updated', 'Test Updated'), ('test_deleted', 'Test Deleted'), ('test_deadline_reminder', 'Test Deadline Reminder'), ('submission_created', 'Submission Created'), ('submission_graded', 'Submission Graded'), ('submission_returned', 'Submission Returned'), ('submission_auto_submitted', 'Submission Auto-Submitted')], max_length=50),
        ),
    ]
