# Generated by Django 5.2.1 on 2025-06-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_username_user_title_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='program_type',
            field=models.CharField(blank=True, choices=[('certificate', 'Certificate'), ('diploma', 'Diploma')], max_length=20, null=True),
        ),
    ]
