# Generated by Django 5.2.1 on 2025-08-29 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='max_points',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='max_score',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='score',
        ),
        migrations.AddField(
            model_name='question',
            name='max_points',
            field=models.FloatField(default=1.0, help_text='Maximum points possible for this question'),
        ),
        migrations.AddField(
            model_name='test',
            name='total_points',
            field=models.FloatField(default=0.0, help_text='Total possible points for this test'),
        ),
    ]
