# Generated by Django 5.2.1 on 2026-05-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_remove_answer_max_points_remove_submission_max_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='grading_history',
            field=models.JSONField(blank=True, default=list, help_text='List of previous grading events: [{grader_id, grader_name, graded_at, score, feedback, per_answer}]'),
        ),
    ]
