# Generated by Django 5.2.1 on 2026-05-03 10:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_add_grading_history_to_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='max_points',
            field=models.FloatField(default=1.0, help_text='Maximum points possible for this question', validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
