version: '3.8'

services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
      args:
        - VITE_API_URL=${VITE_API_URL}
    ports:
      - "3002:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    # Mount nginx config for development/testing
    # volumes:
    #   - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
