# Generated by Django 5.2.1 on 2026-06-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_residential_address', models.TextField()),
                ('nationality', models.CharField(max_length=100)),
                ('employment_status', models.CharField(choices=[('EMPLOYED', 'Employed'), ('UNEMPLOYED', 'Unemployed'), ('STUDENT', 'Student')], max_length=20)),
                ('program_type', models.CharField(choices=[('CERTIFICATE', 'Certificate'), ('DIPLOMA', 'Diploma')], max_length=20)),
                ('program_interest', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
