# Generated by Django 5.2.1 on 2025-06-02 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: list[str] = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_time', models.DateTimeField()),
                ('leave_time', models.DateTimeField(null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('via_recording', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=90)),
                ('zoom_meeting_id', models.CharField(max_length=50, null=True)),
                ('zoom_join_url', models.URLField(null=True)),
                ('recording_url', models.URLField(null=True)),
            ],
        ),
    ]
