# Generated by Django 5.2.1 on 2025-06-02 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['join_time'], 'verbose_name': 'Attendance', 'verbose_name_plural': 'Attendances'},
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['scheduled_at'], 'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
    ]
