# Generated by Django 5.2.1 on 2025-08-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_alter_class_lecturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='password_for_recording',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='password_for_zoom',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='recording_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='zoom_join_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='zoom_meeting_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
