# Generated by Django 5.2.1 on 2025-08-30 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_class_password_for_recording_class_password_for_zoom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
